# This script automatically updates the table of contents and then cleans your local directory

# Inserts an updated Table of Contents into README.md
./tools/toc-gen --insert README.md


# Removes all the tempory files generated by the above script
rm README.md.*
